# -*- coding: utf-8 -*-
"""get_A_stocks_list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16pKciiBGlRBKedkuEl1Q6ahGozpOkEMk
"""

!pip install akshare

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

import akshare as ak
stock_info_a_code_name_df = ak.stock_info_a_code_name()
print(stock_info_a_code_name_df)

with open('/content/drive/MyDrive/513/A_stocks_info.txt', 'w') as f:
 f.write(stock_info_a_code_name_df.to_string(index=False))

df = pd.read_csv('/content/drive/MyDrive/513/A_stocks_info.csv')

print(df)

mask = (
    ~stock_info_a_code_name_df.iloc[:, 1].str.contains('ST', na=False)
    | stock_info_a_code_name_df.iloc[:, 0].str.startswith('688')
)
clean_df = df[mask]

print(clean_df)

clean_df['code'] = df['code'].astype(str).str.zfill(6)

clean_df.to_csv('/content/drive/MyDrive/513/A_stocks_info_clean.csv', index=False)

with open('/content/drive/MyDrive/513/A_stocks_info_clean.txt', 'w') as f:
 f.write(clean_df.to_string(index=False))

df = pd.read_csv('/content/drive/MyDrive/513/A_stocks_info_clean.csv')

print(df)

# 方法2：转换为列表后拼接
codes_list = df['code'].tolist()

print(codes_list)

codes_str = ''
for code in codes_list:
  codes_str += str(code).zfill(6) + ','

print(codes_str)

with open('/content/drive/MyDrive/513/A_stocks_info_clean_list.txt', 'w') as f:
 f.write(codes_str)